// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM7EeuPekGbbV2z3Pf42tfnzcfWJ2N7m0',
    appId: '1:545178034865:web:a63454400e8d6e003df890',
    messagingSenderId: '545178034865',
    projectId: 'yoyaku-mate-provider',
    authDomain: 'yoyaku-mate-provider.firebaseapp.com',
    storageBucket: 'yoyaku-mate-provider.firebasestorage.app',
    measurementId: 'G-8XKK441NE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2TuBl5sbMk6Kcxy7ih3shLA1H_wW-JGI',
    appId: '1:545178034865:android:c795902d2255409b3df890',
    messagingSenderId: '545178034865',
    projectId: 'yoyaku-mate-provider',
    storageBucket: 'yoyaku-mate-provider.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzsm-xa6zbc4EtfduK5umgDTdpC-E7AMQ',
    appId: '1:545178034865:ios:31afc90c9e1663b13df890',
    messagingSenderId: '545178034865',
    projectId: 'yoyaku-mate-provider',
    storageBucket: 'yoyaku-mate-provider.firebasestorage.app',
    iosBundleId: 'com.example.yoyakuMateProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzsm-xa6zbc4EtfduK5umgDTdpC-E7AMQ',
    appId: '1:545178034865:ios:31afc90c9e1663b13df890',
    messagingSenderId: '545178034865',
    projectId: 'yoyaku-mate-provider',
    storageBucket: 'yoyaku-mate-provider.firebasestorage.app',
    iosBundleId: 'com.example.yoyakuMateProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM7EeuPekGbbV2z3Pf42tfnzcfWJ2N7m0',
    appId: '1:545178034865:web:82481117f25eedab3df890',
    messagingSenderId: '545178034865',
    projectId: 'yoyaku-mate-provider',
    authDomain: 'yoyaku-mate-provider.firebaseapp.com',
    storageBucket: 'yoyaku-mate-provider.firebasestorage.app',
    measurementId: 'G-XW74KBQRNC',
  );
}
